name: Bart
config:
  embed_dim: ${dim}$
  residual_depth: ${depth}$
  num_codes: ${codes}$
  use_sep_token: true
  handler: baseline
  use_pretrained_model: ${pretrain}$
  num_layers: ${attnlayers}$
  num_attention_heads: ${attnheads}$