name: Depth${model.config.residual_depth}-C${model.config.num_codes}
config:
  embed_dim: 768
  residual_depth: ${depth}$
  num_codes: ${codes}$
  use_sep_token: true
  commitment_cost: ${cost}$
  handler: quant